export const tamaguiFonts = {
    "Inter-Medium": require('@tamagui/font-inter/otf/Inter-Medium.otf'),
    "Inter-Bold": require('@tamagui/font-inter/otf/Inter-Bold.otf'),
    "Inter-Black": require('@tamagui/font-inter/otf/Inter-Black.otf'),
    "Inter-ExtraBold": require('@tamagui/font-inter/otf/Inter-ExtraBold.otf'),
    "Inter-ExtraLight": require('@tamagui/font-inter/otf/Inter-ExtraLight.otf'),
    "Inter-Light": require('@tamagui/font-inter/otf/Inter-Light.otf'),
    "Inter-Regular": require('@tamagui/font-inter/otf/Inter-Regular.otf'),
    "Inter-SemiBold": require('@tamagui/font-inter/otf/Inter-SemiBold.otf'),
    "Inter-Thin": require('@tamagui/font-inter/otf/Inter-Thin.otf'),
    "Inter-Italic": require('@tamagui/font-inter/otf/Inter-Italic.otf'),
    "Inter-BoldItalic": require('@tamagui/font-inter/otf/Inter-BoldItalic.otf'),
    "Inter-BlackItalic": require('@tamagui/font-inter/otf/Inter-BlackItalic.otf'),
    "Inter-ExtraBoldItalic": require('@tamagui/font-inter/otf/Inter-ExtraBoldItalic.otf'),
    "Inter-ExtraLightItalic": require('@tamagui/font-inter/otf/Inter-ExtraLightItalic.otf'),
    "Inter-LightItalic": require('@tamagui/font-inter/otf/Inter-LightItalic.otf'),
    "Inter-SemiBoldItalic": require('@tamagui/font-inter/otf/Inter-SemiBoldItalic.otf'),
    "Inter-ThinItalic": require('@tamagui/font-inter/otf/Inter-ThinItalic.otf'),
    Silkscreen: require('@tamagui/font-silkscreen/files/slkscr.ttf'),
    "Silkscreen-Bold": require('@tamagui/font-silkscreen/files/slkscrb.ttf'),
};
