import type {AppProps} from 'next/app';
import Head from 'next/head';
import {ReactNode} from 'react';
import {StyleSheet} from 'react-native';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import {SafeAreaProvider} from 'react-native-safe-area-context';

const insets = {
  top: 0,
  right: 0,
  bottom: 0,
  left: 0,
};

const frame = {
  x: 0,
  y: 0,
  width: 0,
  height: 0,
};

const initialMetrics = {insets, frame};

const Providers = ({children}: {children: ReactNode}) => {
  return (
    <SafeAreaProvider
      initialMetrics={initialMetrics} //https://github.com/th3rdwave/react-native-safe-area-context#web-ssr
    >
      <GestureHandlerRootView style={styles.container}>
        {children}
      </GestureHandlerRootView>
    </SafeAreaProvider>
  );
};

export default function MyApp({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>🌒 Luna App</title>
        <meta name="description" content="Generated by 🌒 Luna" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <Providers>
        <Component {...pageProps} />
      </Providers>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
