import type {AppProps} from 'next/app';
import '../styles.css';
import Head from 'next/head';

export default function MyApp({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>🌒 Luna App</title>
        <meta name="description" content="Generated by 🌒 Luna" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <Component {...pageProps} />
    </>
  );
}
