import type {AppProps} from 'next/app';
import {
  initialWindowMetrics,
  SafeAreaProvider,
} from 'react-native-safe-area-context';
import {useStyles} from '../hooks';
import '../styles.css';
import Head from 'next/head';

export default function MyApp({Component, pageProps}: AppProps) {
  const {backgroundStyle} = useStyles();

  return (
    <SafeAreaProvider
      initialMetrics={initialWindowMetrics}
      style={backgroundStyle}>
      <Head>
        <title>🌒 Luna App</title>
        <meta name="description" content="Generated by 🌒 Luna" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <Component {...pageProps} />
    </SafeAreaProvider>
  );
}
