name: Code Quality Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'template/**'
  push:
    branches:
      - master
    paths:
      - 'template/**'

jobs:
  linting:
    name: Linting (eslint, prettier, tsc)
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
          token: ${{ secrets.LUNA_PAT }}
          repository: criszz77/luna
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: cd template && echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        uses: nick-invision/retry@v2.8.3
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: cd template && yarn --no-audit --prefer-offline
      - name: Lint
        run: cd template && yarn lint:all
