name: Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "template/**"
  push:
    branches:
      - main
    paths:
      - "template/**"

jobs:
  jest:
    name: Jest
    timeout-minutes: 50
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: cd template && echo "{dir}={$(yarn cache dir)}" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        uses: nick-invision/retry@v2.8.3
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 4
          command: cd template && yarn --no-audit --prefer-offline
      - name: Jest
        run: cd template && yarn test:jest
